In [1]:
# Import custom functions
import api
import data_cleaning as dc
import feature_engineering as fe
import train as tr

# Importing the most recent data
url = 'https://moneypuck.com/moneypuck/playerData/careers/gameByGame/all_teams.csv'
rawData = api.api_call(url)
print("** The raw data has been successfully downloaded.")

# Cleaning the rawData
cleanData = dc.clean(rawData)
print("** The raw data has been successfully cleaned.")

# Feature Engineering using the cleanData
df = fe.fengine(cleanData)
print("** Feature Engineering has been successfully completed.")

** The raw data has been successfully downloaded.
** The raw data has been successfully cleaned.
** Feature Engineering has been successfully completed.

In [2]:
df.head()

,team,season,name,gameId,playerTeam,opposingTeam,Shootout Game,OT Game,Win,Loss,...,totalShotCreditAgainst,scoreAdjustedTotalShotCreditAgainst,scoreFlurryAdjustedTotalShotCreditAgainst,playoffGame,year,month,day,home_or_away#,team#,opposingTeam#
4341,NYR,2019,NYR,2019020006,NYR,WPG,0,0,1,0,...,3.520,3.628,3.600,0,2019,10,3,1,19,30
4346,NYR,2019,NYR,2019020020,NYR,OTT,0,0,1,0,...,2.086,1.965,1.911,0,2019,10,5,0,19,20
4351,NYR,2019,NYR,2019020061,NYR,EDM,0,0,0,1,...,3.636,3.730,3.707,0,2019,10,12,1,19,11
4356,NYR,2019,NYR,2019020100,NYR,NJD,0,0,0,1,...,3.852,3.829,3.793,0,2019,10,17,0,19,16
4361,NYR,2019,NYR,2019020109,NYR,WSH,0,0,0,1,...,4.353,4.340,4.118,0,2019,10,18,0,19,31

In [4]:
# Column average based on specific team
avg_totalShotCreditAgainst = df.loc[df["team"] == 'NYR', "totalShotCreditAgainst"].mean()
print(avg_totalShotCreditAgainst)

# Find average of an entire column
col_avg_totalShotCreditAgainst = df['totalShotCreditAgainst'].mean()
print(col_avg_totalShotCreditAgainst)

2.862887179487179
2.8489017946161512